### ISSUE TITLE
prussdrv_open open failed

### ISSUE THREAD

**Issue by vmayoral** [beagleboard/am335x_pru_package#16]
I've been able to compile everything following [these steps](https://github.com/erlerobot/wiki/wiki/Getting-started-with-the-PRU) but i get the following error when trying to run the examples:

```
./PRU_memAccessPRUDataRam
INFO: Starting PRU_memAccessPRUDataRam example.
prussdrv_open open failed
```

**Comment by Hitheshkaranth** [comment]
I was trying the same thing and it took me to another problem. When I try to enable the PRU, I get this error:

root@beaglebone:~# echo BB-BONE-PRU-01 >/sys/devices/bone_capemgr.8/slots
sh: echo: write error: No such file or directory

Did you come across the same problem? How can I resolv it?
Thank you.

- Make sure you add the .dtbo file upon compilation to /lib/firmware 
- in SU mode  "echo BB-BONE-PRU-01 >/sys/devices/bone_capemgr.8/slots"
- if you are using Beaglebone Black then " echo BB-BONE-PRU-01 >/sys/devices/platform/bone_capemgr/slots"
Thank you
