### ISSUE TITLE
where to register errata to am335xPruReferenceGuide.pdf

### ISSUE THREAD

**Issue by gomer-grondin** [beagleboard/am335x_pru_package#34]
I've noticed but not noted at least a half dozen typo's / errors in this guide (June 2013).  I'd be happy to record them for you if there is a definitive place for them.  First example is page 58 where there is no difference in 'Operation' of MIN and MAX, and the only difference in the 'Definition' is the opcode.

**Comment by jadonk** [comment]
This is the place for the community to collaborate on the package.

**Comment by jadonk** [comment]
@gomer-grondin Please report the specific issues.
